export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const STORE_UID = 'STORE_UID';

export const INVALIDATE_USER_PROFILE = 'INVALIDATE_USER_PROFILE';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const INVALIDATE_MY_EVENTS = 'INVALIDATE_MY_EVENTS';
export const REQUEST_MY_EVENTS = 'REQUEST_MY_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const FAIL_MY_EVENTS = 'FAIL_MY_EVENTS';

export const CHANGE_CAROUSEL_HEIGHT = 'CHANGE_CAROUSEL_HEIGHT';
export const TOGGLE_EVENT_CAROUSEL = 'TOGGLE_EVENT_CAROUSEL';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';

export const TOGGLE_LANDING_CAROUSEL = 'TOGGLE_LANDING_CAROUSEL';
export const RESET_AUTH = 'RESET_AUTH';
export const SET_MODE = 'SET_MODE';

export const SET_VERIFICATION_CODE = 'SET_VERIFICATION_CODE';
export const SET_CONFIRM_RESULT = 'SET_CONFIRM_RESULT';
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const PHONE_AUTH_ERROR = 'PHONE_AUTH_ERROR';
export const SET_TEMP_UID = 'SET_TEMP_UID';

export const SET_PROFILE_PICTURE = 'SET_PROFILE_PICTURE';
export const USER_DETAILS_ERROR = 'USER_DETAILS_ERROR';
export const CREATE_USERNAME = 'CREATE_USERNAME';
export const SET_USER_STATE = 'SET_USER_STATE';

export const SELECT_EVENT_PAGE = 'SELECT_EVENT_PAGE';
export const SET_EVENT_TYPE = 'SET_EVENT_TYPE';

export const SET_CREATE_PAYLOAD = 'SET_CREATE_PAYLOAD';
export const TOGGLE_CREATE_STAGE = 'TOGGLE_CREATE_STAGE';
export const RESET_CREATE_EVENT = 'RESET_CREATE_EVENT';

export const QUERY_EVENT_FROM_KEY = 'QUERY_EVENT_FROM_KEY';
export const QUERY_EVENT_FAIL = 'QUERY_EVENT_FAIL';
export const SAVE_EVENT_DATA = 'SAVE_EVENT_DATA';
export const RESET_EVENT_QUERY = 'RESET_EVENT_QUERY';
